### ISSUE TITLE
Deploy / Publish error

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1656]
It seems we now have an error while publishing a new version. Maybe is it related to #1650 ? 

Here is the error : 
```
[12:38:40 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:38:40 PM] [semantic-release] › ℹ  The next release version is 40.7.0
[12:38:40 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:38:40 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:38:40 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[12:38:41 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[12:38:41 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed with exit code 1: git push --tags https://[secure]@github.com/cozy/cozy-ui.git HEAD:undefined
    at makeError (/home/travis/build/cozy/cozy-ui/node_modules/@semantic-release/git/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/home/travis/build/cozy/cozy-ui/node_modules/@semantic-release/git/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command:
   'git push --tags https://[secure]@github.com/cozy/cozy-ui.git HEAD:undefined',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr:
   'error: The destination you provided is not a full refname (i.e.,\nstarting with "refs/"). We tried to guess what you meant by:\n\n- Looking for a ref that matches \'undefined\' on the remote side.\n- Checking if the <src> being pushed (\'HEAD\')\n  is a ref in "refs/{heads,tags}/". If so we add a corresponding\n  refs/{heads,tags}/ prefix on the remote side.\n\nNeither worked, so we gave up. You must fully qualify the ref.\nhint: The <src> part of the refspec is a commit object.\nhint: Did you mean to create a new branch by pushing to\nhint: \'HEAD:refs/heads/undefined\'?\nerror: failed to push some refs to \'https://github.com/cozy/cozy-ui.git\'',
  failed: true,```

see https://travis-ci.com/github/cozy/cozy-ui/builds/200345792#L2095-L2113

**Comment by ptbrowne** [comment]
Fixed, thanks.
